### ISSUE TITLE
Software Error In Amd64 Kaillinux Linux

### ISSUE THREAD

**Issue by nios34** [360PegasusTeam/GhostTunnel#2]
ghost_tunnel>help
COMMANDS:

	sessions = list all clients
	use = select a client to operate, use [clientID]
	exit = exit current operation
	wget = download a file from a client, wget [filepath]
	quit = quit ghost tunnel
	help = show this usage help

ghost_tunnel>use段错误

Enter "use" in the console,Return error

**Comment by nios34** [comment]
gayhub/GhostTunnel/src/ghosttunnel: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=582762e989b0d54973df728d17e8960de15227fe, with debug_info, not stripped

gcc version 8.2.0 (Debian 8.2.0-7)

Linux kali 4.18.0-kali1-amd64 #1 SMP Debian 4.18.6-1kali1 (2018-09-10) x86_64 GNU/Linux

**Comment by saidortiz** [comment]
hi @nios34 
did you manage to list all the clients?
