### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by shepardac** [360PegasusTeam/GhostTunnel#5]
So this might be a dumb question. I was looking for some clarification on usage. Do both PC running linux and Ghost Tunnel need to be up? right now I have 2 linux machines with alfa cards in monitor mode and running ghost tunnel. When I use commands sessions I see no devices. However if I run airodump-ng my cards picks up networks. Am I missing a step in regards to running this program? Thank you

**Comment by saidortiz** [comment]
i have the same issue, i can run the script, but i can see any devices.

**Comment by qingxp9** [comment]
@shepardac @saidortiz 
You should first release the payload on a victim laptop(like a Windows). If it goes well, you will see the victim in the ghosttunnel console.

There is a demo which may be helpful: https://www.youtube.com/watch?v=2s7qFLCafSI

**Comment by saidortiz** [comment]
@qingxp9  awesome, thx for the video.

**Comment by shandongtlb** [comment]
> @shepardac @saidortiz
> You should first release the payload on a victim laptop(like a Windows). If it goes well, you will see the victim in the ghosttunnel console.
> 
> There is a demo which may be helpful: https://www.youtube.com/watch?v=2s7qFLCafSI

i have the same issue,i use nethunter,when i launch airmon-ng start wlan1,it works.but when i use iwconfig wlan1 mode monitor,it will not work,it will tell me "monitor operation not supported"
