### ISSUE TITLE
bad work

### ISSUE THREAD

**Issue by shandongtlb** [360PegasusTeam/GhostTunnel#6]
i have the same issue,i use nethunter,when i launch airmon-ng start wlan1,it works.but when i use iwconfig wlan1 mode monitor,it will not work,it will tell me "monitor operation not supported"

**Comment by qingxp9** [comment]
Have you checked your wifi card support monitor mode?

**Comment by shandongtlb** [comment]
> Have you checked your wifi card support monitor mode?

It's RT3070L,when I use my kali on desktop working.
